from datetime import UTC, datetime, timedelta

from xunlei_zhiqu_runtime.models import ResourceJobSnapshot


def fixture_jobs() -> list[ResourceJobSnapshot]:
    """Small stage-B fixture set for the task center."""
    now = datetime.now(UTC)
    return [
        ResourceJobSnapshot(
            job_id="job_zhiqu_001",
            title="Example App 5.2.1",
            subtitle="Windows x64 便携版 · 中文语言包 · 校验文件",
            kind="zhiqu",
            status="downloading",
            progress=68.4,
            downloaded_bytes=1_842_000_000,
            total_bytes=2_692_000_000,
            speed_bytes_per_second=12_600_000,
            eta_seconds=68,
            stage_label="正在下载主资源",
            next_action="pause",
            source_count=3,
            excluded_count=15,
            created_at=now - timedelta(minutes=18),
            destination="D:/Downloads/Example App 5.2.1",
            delivery_target="local",
            resource_type="software",
            plan_overview="节点 A 识别为 Windows 软件包，优先选择当前设备可直接使用的 x64 便携版，并保留中文语言包与校验文件。",
            selected_items=["Windows x64 便携版", "中文语言包", "SHA-256 校验文件"],
            alternative_count=2,
            source_page="https://example.test/downloads",
        ),
        ResourceJobSnapshot(
            job_id="job_zhiqu_002",
            title="Open Media Course · 1080p",
            subtitle="12 个视频 · 中文字幕 · 2 个备用来源",
            kind="zhiqu",
            status="waiting_for_source",
            progress=42.0,
            downloaded_bytes=3_210_000_000,
            total_bytes=7_643_000_000,
            speed_bytes_per_second=0,
            eta_seconds=None,
            stage_label="云盘来源失效，等待继续获取",
            issue="主来源返回 503，原页面、候选与 42% 进度均已保留。",
            next_action="continue_acquisition",
            source_count=2,
            excluded_count=8,
            created_at=now - timedelta(hours=1, minutes=12),
            destination="迅雷云盘/智取下载/Open Media Course",
            delivery_target="cloud",
            resource_type="video",
            plan_overview="节点 A 选择 1080p 主视频、中文字幕与课程附件，备用来源保留但暂不重复下载。",
            selected_items=["1080p 主视频组", "简体中文字幕", "课程附件"],
            alternative_count=2,
            source_page="https://media.example.test/course",
        ),
        ResourceJobSnapshot(
            job_id="job_normal_001",
            title="sample-dataset.zip",
            subtitle="普通下载 · ZIP 压缩包",
            kind="normal",
            status="completed",
            progress=100,
            downloaded_bytes=482_000_000,
            total_bytes=482_000_000,
            speed_bytes_per_second=0,
            eta_seconds=None,
            stage_label="已完成",
            next_action="open",
            source_count=1,
            excluded_count=0,
            created_at=now - timedelta(days=1),
            destination="D:/Downloads/sample-dataset.zip",
            delivery_target="local",
            resource_type="archive",
            plan_overview="普通链接任务。",
            selected_items=["sample-dataset.zip"],
            source_page="https://data.example.test/datasets",
        ),
        ResourceJobSnapshot(
            job_id="job_zhiqu_003",
            title="Open Tools Pack 2026.08",
            subtitle="Windows x64 安装包 · 文档 · SHA-256 校验文件",
            kind="zhiqu",
            status="completed",
            progress=100,
            downloaded_bytes=734_000_000,
            total_bytes=734_000_000,
            speed_bytes_per_second=0,
            eta_seconds=None,
            stage_label="已保存到云盘",
            next_action="open",
            source_count=2,
            excluded_count=6,
            created_at=now - timedelta(days=2, hours=3),
            destination="迅雷云盘/智取下载/Open Tools Pack 2026.08",
            delivery_target="cloud",
            resource_type="software",
            plan_overview="安装包、使用文档与校验文件已作为一个资源目标完成交付。",
            selected_items=["Windows x64 安装包", "使用文档", "SHA-256 校验文件"],
            alternative_count=1,
            source_page="https://tools.example.test/releases",
        ),
    ]
